version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16 # Specify the Node.js version (use the one your project needs)
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React application...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
